# ARCHISHA SINHA

In [1]:
import numpy as np

# Create a 3x4 array filled with zeros
z = np.zeros([3, 4])

# Print the array and its number of dimensions
print(z)
print(z.ndim)
print()

# Define arrays X and Y
X = [0, 1, 2]
Y = [0, 1, 2, 3]

# Get the lengths of arrays X and Y
a = len(X)
b = len(Y)

# Populate the array z based on the formula ((2*x) + (3*y))/55
for x in range(a):
    for y in range(b):
        z[x, y] = ((2 * x) + (3 * y)) / 55

# Print the populated array
print(z)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2

[[0.         0.05454545 0.10909091 0.16363636]
 [0.03636364 0.09090909 0.14545455 0.2       ]
 [0.07272727 0.12727273 0.18181818 0.23636364]]


# Marginal Probability Mass Functions (PMF) for random variables X and Y from a given joint probability distribution

In [2]:
from scipy.stats.contingency import margins

# Assuming you have the joint probability distribution in `z`
joint_probability_X_Y = np.array(z)

# Calculate the marginal PMFs for X and Y using the `margins` function
x_marginal, y_marginal = margins(joint_probability_X_Y)

print("Marginal PMF of X:")
print(X)  # Values of random variable X
print()
pmf_x = x_marginal
print(pmf_x)  # Marginal PMF of X

print()
print("Marginal PMF of Y:")
print(Y)  # Values of random variable Y
print()
pmf_y = y_marginal
print(pmf_y)  # Marginal PMF of Y


Marginal PMF of X:
[0, 1, 2]

[[0.32727273]
 [0.47272727]
 [0.61818182]]

Marginal PMF of Y:
[0, 1, 2, 3]

[[0.10909091 0.27272727 0.43636364 0.6       ]]


# Claculating Mean and Variance of the random variable X based on its Probability Mass Function (PMF)

In [3]:
import numpy as np

# Assuming you have the values of random variable X and its PMF
a = np.array(X)  # Values of X
print("Values of X:")
print(a)
print()

# Print the dimension of X
print("Dimension of X:")
print(a.ndim)

# Print the dimension of the PMF of X
print("Dimension of PMF of X:")
print(pmf_x.ndim)

# Print the shape of list X
print("Shape of X:")
print(a.shape)

b = pmf_x  # PMF of X
print("PMF of X:")
print(b)

# Print the shape of PMF of X
print("Shape of PMF of X:")
print(b.shape)

# Reshape a and b to (3, 1) shape
a.shape = (a.size, 1)
b.shape = (b.size, 1)

print("Reshaped Shape of X:")
print(a.shape)  # (3, 1)

print("Reshaped Shape of PMF of X:")
print(b.shape)  # (3, 1)

# Calculate the mean of X: mu_x = Sum(x * P(x))
c = a * b
print("X * PMF of X:")
print(c)
print()

mu_x = np.sum(c)
print("Mean of X is {}".format(mu_x))
print()

# Calculate the variance of X: Var(X) = E[X^2] - (E[X])^2
var_x = np.sum(a**2 * b) - (mu_x**2)
print("Variance of X is {}".format(var_x))

Values of X:
[0 1 2]

Dimension of X:
1
Dimension of PMF of X:
2
Shape of X:
(3,)
PMF of X:
[[0.32727273]
 [0.47272727]
 [0.61818182]]
Shape of PMF of X:
(3, 1)
Reshaped Shape of X:
(3, 1)
Reshaped Shape of PMF of X:
(3, 1)
X * PMF of X:
[[0.        ]
 [0.47272727]
 [1.23636364]]

Mean of X is 1.709090909090909

Variance of X is 0.02446280991735561
